# Generated by Django 4.2.10 on 2024-03-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_request_requestid'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('datePost', models.DateField()),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.admin')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.item')),
            ],
        ),
        migrations.CreateModel(
            name='PostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.post')),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.request')),
            ],
        ),
    ]
