# Generated by Django 4.2.10 on 2024-03-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_post_postrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Password',
            new_name='password',
        ),
    ]
