# Generated by Django 4.2.10 on 2024-04-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_rename_password_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datePost',
            field=models.DateTimeField(),
        ),
    ]
