# Generated by Django 4.2.10 on 2024-03-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('cateName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeID', models.AutoField(primary_key=True, serialize=False)),
                ('placeCode', models.CharField(max_length=3)),
                ('placeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCateID', models.AutoField(primary_key=True, serialize=False)),
                ('subCateName', models.CharField(max_length=100)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('placeDetail', models.TextField()),
                ('itemDetail', models.TextField()),
                ('image', models.CharField(max_length=512)),
                ('isApproved', models.BooleanField(default=False)),
                ('dateLost', models.DateField()),
                ('dateRequest', models.DateField(auto_now_add=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.place')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('itemDetail', models.TextField()),
                ('placeDetail', models.TextField()),
                ('image', models.CharField(max_length=512)),
                ('isFound', models.BooleanField(default=False)),
                ('dateFound', models.DateField()),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.place')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
