# Generated by Django 4.2.10 on 2024-05-19 10:54

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('tel', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('cateName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeID', models.IntegerField(primary_key=True, serialize=False)),
                ('placeCode', models.CharField(max_length=3)),
                ('placeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('tel', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Lost item', max_length=256)),
                ('itemDetail', models.TextField()),
                ('placeDetail', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('datePost', models.DateTimeField()),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.place')),
            ],
        ),
    ]
