# Generated by Django 4.2.10 on 2024-03-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
