# Generated by Django 4.2.10 on 2024-05-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
